# Copyright (C) 2015 TopCoder Inc., All Rights Reserved.
# 
# This file describes the database configuration of the app.
#
# Author TCSASSEMBLER
# Version 1.0

development:
  adapter: postgresql
  encoding: unicode
  database: enphase_demo_dev
  pool: 5
  username: vijayarajmurugesan
  password:

# development:
#   adapter: mysql2
#   encoding: utf8
#   database: gitlab1
#   pool: 5
#   host: 127.0.0.1
#   username: root
#   password:
  
test:
  adapter: postgresql
  encoding: unicode
  database: enphase_demo_test
  pool: 5
  username: vijayarajmurugesan
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: enphase_demo_prod
#   pool: 5
#   username: vijayaraj
#   password:

production:
  adapter: mysql2
  encoding: utf8
  database: enphase_demo_prod
  pool: 5
  host: 127.0.0.1
  username: root
  password:

  